-- Run as an administrator in Snowsight, once. No password in this file.
-- Replace PUBLIC_KEY_REPLACE with the ONE-LINE contents of secrets/snowflake_public_key.txt.
-- If using an existing service user, adapt only the user statements; keep the limited role.
USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS RUTANOVA_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS RUTANOVA DATA_RETENTION_TIME_IN_DAYS = 1;
CREATE SCHEMA IF NOT EXISTS RUTANOVA.RAW;
CREATE SCHEMA IF NOT EXISTS RUTANOVA.ANALYTICS;
CREATE ROLE IF NOT EXISTS RUTANOVA_ROLE;
GRANT USAGE ON WAREHOUSE RUTANOVA_WH TO ROLE RUTANOVA_ROLE;
GRANT USAGE ON DATABASE RUTANOVA TO ROLE RUTANOVA_ROLE;
GRANT USAGE ON SCHEMA RUTANOVA.RAW TO ROLE RUTANOVA_ROLE;
GRANT USAGE ON SCHEMA RUTANOVA.ANALYTICS TO ROLE RUTANOVA_ROLE;
GRANT CREATE TABLE ON SCHEMA RUTANOVA.RAW TO ROLE RUTANOVA_ROLE;  
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA RUTANOVA.ANALYTICS TO ROLE RUTANOVA_ROLE;
CREATE USER IF NOT EXISTS RUTANOVA_SVC TYPE = SERVICE
  DEFAULT_ROLE = RUTANOVA_ROLE DEFAULT_WAREHOUSE = RUTANOVA_WH;
ALTER USER RUTANOVA_SVC SET RSA_PUBLIC_KEY = PUBLIC_KEY_REPLACE;

GRANT ROLE RUTANOVA_ROLE TO USER RUTANOVA_SVC;
-- ACCOUNTADMIN owns the database; pipeline owns only the tables/views it creates.
-- Give the human reviewing results the role, using their REAL username:
-- GRANT ROLE RUTANOVA_ROLE TO USER YOUR_REVIEWER_USER;
